apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "MyAwesomeFlogoService"
  description: "This integrates everything with everything"
  links:
    - title: TIBCO Cloud Home
      url: https://cloud.tibco.com/
    - title: Documentation
      url: https://eu.integration.cloud.tibco.com/docs/index.html
    - title: TIBCO Cloud Integration
      url: https://eu.integration.cloud.tibco.com/applications
  annotations:
    github.com/project-slug: hpeters83/my-flogo-service-demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: development
  owner: "HPeters"
